.TH fumosay 1 "2024 May 20" "version 1.1.7"
.SH NAME
fumosay - funky talking fumofumos

.SH SYNOPSIS
fumosay
.BI "[-hlng] [-c" "color" "] [-W " "column" "] [-f " "name(s)" "] [-E " "expression" "]"

.SH EXAMPLES
.IP "fumosay Hello world!"
.IP "fortune | fumosay -c -f alice,marisa -E 3"
Have Alice or Marisa read out the output of fortune, with colored text and a smile.

.SH DESCRIPTION
.I fumosay
draws an ASCII art of a FumoFumo plushie saying something the user provided. If no message is in the command line, fumos will read from standard input. The fumo will word-wrap the message at 80 columns and print it out on standard output.

.SH OPTIONS
.TP
.B -l
List the names of all available fumos.
.TP
.B -n
Disable word-wrapping, preserving white-spaces and line breaks. Allowing the fumo to say another fumo.
.TP
.B -g
Display a simple prompt at the top of the message, like a video game dialogue.
.TP
.BI "-c" "R,G,B"
Color the text with a color that vaguely represents the fumo. Optionally, specify an RGB color of your own, there are no spaces after the character c.
.TP
.BR "-W " "column"
Specify where the message should be word-wrapped, the default is 80. This option is
.I ignored
.RB "if " "-n " "is set."
.TP
.BR "-f " "name"
Specify specific fumos to read your message. For more than one name, separate them with ",", one will be picked at random among them.
.TP
.BR "-E " "expression"
Set an alternate expression (mouth string) for the fumo. You may choose a preset from the following or specify your own custom expression.
.RS
.br
\'1\' - frowny
.br
\'2\' - neutral
.br
\'3\' - smile
.br
\'4\' - bigger smile
.br
\'v\' - little vampire sister
.br
\'w\' - lucky bunny :3
.br
\'b\' - is for baka
.br
\'r\' - pick randomly
.PP
To specify a custom expression, enter anything longer than one character. The first 24 characters of the input will be used, if fewer than 24 characters is given, the space will be filled by spaces automatically. The 24 characters will be split into 3 separate lines of 8 characters each. The center of each line is located at the 5th position out of 8. The following example produces a 3-wide smile in the middle of line 2. There are 11 leading spaces.
.sp
fumosay -E "           *_*"
.RE
.TP
.B -h
Display help message.
.TP
.B -v
Display version.

.SH ADDING FUMOS
The quote-unquote configuration file "fumo.fumo" is really just C code with instructions. You can add new fumos to it and recompile fumosay.

.SH BUGS
Fumosay assumes every byte in the input is a 1-cell-wide printable character, other characters will break the textbox and might not be displayed properly.

.SH SEE ALSO
.IR "cowsay" "(1), " "FORTUNE" "(6)"
.sp
The FumoFumos are adorable friendly plushies (mainly) featuring characters from Touhou Project, made by Gift!
.br
The ASCII arts are created with help from the tool of asciiart.eu.
.br
fumosay is inspired by Tony Monroe's cowsay.
